global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-cicd-windows
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  master:
    parameter_input: cicd-windows-master.json
    regions:
      - ap-southeast-1
      - ap-southeast-2
      - eu-west-1
      - us-east-1
      - us-east-2
      - us-west-2
    template_file: cicd-windows-master.template
